import { Inter } from "next/font/google";
import "./globals.css";
import CustomNavbar from "@/components/customNavbar";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <CustomNavbar></CustomNavbar>
        <div className="mt-2">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
